version: '3'
services:
  app:
    image: app-devops-image
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=eXitvoid
      - MYSQL_DATABASE=devopsproject
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=eXitvoid
      - MYSQL_DATABASE=devopsproject
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
